// Response Codes Mapping
export const RESPONSE_CODES = {
  // Success Codes
  SUCCESS: 'RC_200',
  CREATED: 'RC_201',
  
  // General Error Codes
  BAD_REQUEST: 'RC_400',
  UNAUTHORIZED: 'RC_401',
  FORBIDDEN: 'RC_403',
  NOT_FOUND: 'RC_404',
  VALIDATION_ERROR: 'RC_422',
  INTERNAL_ERROR: 'RC_500',
  
  // Authentication Codes
  INVALID_CREDENTIALS: 'RC_A001',
  EMAIL_ALREADY_EXISTS: 'RC_A002',
  USER_NOT_FOUND: 'RC_A003',
  TOKEN_EXPIRED: 'RC_A004',
  
  // OTP Codes
  OTP_SENT: 'RC_O001',
  INVALID_OTP: 'RC_O002',
  OTP_EXPIRED: 'RC_O003',
  OTP_NOT_FOUND: 'RC_O004',
  
  // WhatsApp Codes
  WHATSAPP_NOT_CONNECTED: 'RC_W001',
  WHATSAPP_SEND_FAILED: 'RC_W002',
  
  // Email Codes
  EMAIL_SEND_FAILED: 'RC_E001',
  EMAIL_SERVICE_ERROR: 'RC_E002',
  
  // Order Codes
  ORDER_CREATED: 'RC_OR001',
  ORDER_NOT_FOUND: 'RC_OR002',
  ORDER_CANCELLED: 'RC_OR003',
  
  // Station Codes
  STATIONS_FOUND: 'RC_S001',
  STATION_NOT_FOUND: 'RC_S002',
  
  // Payment Codes
  PAYMENT_SUCCESS: 'RC_P001',
  PAYMENT_FAILED: 'RC_P002',
  
  // Review Codes
  REVIEW_CREATED: 'RC_R001',
  REVIEWS_FOUND: 'RC_R002',
  REVIEW_NOT_FOUND: 'RC_R003',
  
  // Notification Codes
  NOTIFICATIONS_FOUND: 'RC_N001',
  NOTIFICATION_MARKED_READ: 'RC_N002',
  NOTIFICATION_SENT: 'RC_N003',
  NOTIFICATION_NOT_FOUND: 'RC_N004',
  
  // Account Management Codes
  ACCOUNT_DELETED: 'RC_AC001'
};

// Response Messages
export const RESPONSE_MESSAGES = {
  [RESPONSE_CODES.SUCCESS]: 'Success',
  [RESPONSE_CODES.CREATED]: 'Created successfully',
  [RESPONSE_CODES.BAD_REQUEST]: 'Bad request',
  [RESPONSE_CODES.UNAUTHORIZED]: 'Unauthorized',
  [RESPONSE_CODES.FORBIDDEN]: 'Forbidden',
  [RESPONSE_CODES.NOT_FOUND]: 'Not found',
  [RESPONSE_CODES.VALIDATION_ERROR]: 'Validation error',
  [RESPONSE_CODES.INTERNAL_ERROR]: 'Internal server error',
  
  [RESPONSE_CODES.INVALID_CREDENTIALS]: 'Invalid credentials',
  [RESPONSE_CODES.EMAIL_ALREADY_EXISTS]: 'Email already exists',
  [RESPONSE_CODES.USER_NOT_FOUND]: 'User not found',
  [RESPONSE_CODES.TOKEN_EXPIRED]: 'Token expired',
  
  [RESPONSE_CODES.OTP_SENT]: 'OTP sent successfully',
  [RESPONSE_CODES.INVALID_OTP]: 'Invalid OTP',
  [RESPONSE_CODES.OTP_EXPIRED]: 'OTP expired',
  [RESPONSE_CODES.OTP_NOT_FOUND]: 'OTP not found',
  
  [RESPONSE_CODES.WHATSAPP_NOT_CONNECTED]: 'WhatsApp not connected',
  [RESPONSE_CODES.WHATSAPP_SEND_FAILED]: 'WhatsApp send failed',
  
  [RESPONSE_CODES.EMAIL_SEND_FAILED]: 'Email send failed',
  [RESPONSE_CODES.EMAIL_SERVICE_ERROR]: 'Email service error',
  
  [RESPONSE_CODES.ORDER_CREATED]: 'Order created successfully',
  [RESPONSE_CODES.ORDER_NOT_FOUND]: 'Order not found',
  [RESPONSE_CODES.ORDER_CANCELLED]: 'Order cancelled',
  
  [RESPONSE_CODES.STATIONS_FOUND]: 'Stations found',
  [RESPONSE_CODES.STATION_NOT_FOUND]: 'Station not found',
  
  [RESPONSE_CODES.PAYMENT_SUCCESS]: 'Payment successful',
  [RESPONSE_CODES.PAYMENT_FAILED]: 'Payment failed',
  
  [RESPONSE_CODES.REVIEW_CREATED]: 'Review created successfully',
  [RESPONSE_CODES.REVIEWS_FOUND]: 'Reviews found',
  [RESPONSE_CODES.REVIEW_NOT_FOUND]: 'Review not found',
  
  [RESPONSE_CODES.NOTIFICATIONS_FOUND]: 'Notifications found',
  [RESPONSE_CODES.NOTIFICATION_MARKED_READ]: 'Notification marked as read',
  [RESPONSE_CODES.NOTIFICATION_SENT]: 'Notification sent successfully',
  [RESPONSE_CODES.NOTIFICATION_NOT_FOUND]: 'Notification not found',
  
  [RESPONSE_CODES.ACCOUNT_DELETED]: 'Account deleted successfully'
};

// Response Utility Functions
export const createSuccessResponse = (responseCode = RESPONSE_CODES.SUCCESS, data = null, customMessage = null) => {
  return {
    success: true,
    message: customMessage || RESPONSE_MESSAGES[responseCode],
    responseCode,
    data,
    timestamp: new Date().toISOString()
  };
};

export const createErrorResponse = (responseCode = RESPONSE_CODES.INTERNAL_ERROR, error = null, customMessage = null) => {
  return {
    success: false,
    message: customMessage || RESPONSE_MESSAGES[responseCode],
    responseCode,
    error,
    timestamp: new Date().toISOString()
  };
};

// HTTP Status Code Mapping
export const HTTP_STATUS = {
  [RESPONSE_CODES.SUCCESS]: 200,
  [RESPONSE_CODES.CREATED]: 201,
  [RESPONSE_CODES.BAD_REQUEST]: 400,
  [RESPONSE_CODES.UNAUTHORIZED]: 401,
  [RESPONSE_CODES.FORBIDDEN]: 403,
  [RESPONSE_CODES.NOT_FOUND]: 404,
  [RESPONSE_CODES.VALIDATION_ERROR]: 422,
  [RESPONSE_CODES.INTERNAL_ERROR]: 500,
  
  [RESPONSE_CODES.INVALID_CREDENTIALS]: 401,
  [RESPONSE_CODES.EMAIL_ALREADY_EXISTS]: 400,
  [RESPONSE_CODES.USER_NOT_FOUND]: 404,
  [RESPONSE_CODES.TOKEN_EXPIRED]: 401,
  
  [RESPONSE_CODES.OTP_SENT]: 200,
  [RESPONSE_CODES.INVALID_OTP]: 400,
  [RESPONSE_CODES.OTP_EXPIRED]: 400,
  [RESPONSE_CODES.OTP_NOT_FOUND]: 400,
  
  [RESPONSE_CODES.WHATSAPP_NOT_CONNECTED]: 503,
  [RESPONSE_CODES.WHATSAPP_SEND_FAILED]: 500,
  
  [RESPONSE_CODES.EMAIL_SEND_FAILED]: 500,
  [RESPONSE_CODES.EMAIL_SERVICE_ERROR]: 503,
  
  [RESPONSE_CODES.ORDER_CREATED]: 201,
  [RESPONSE_CODES.ORDER_NOT_FOUND]: 404,
  [RESPONSE_CODES.ORDER_CANCELLED]: 200,
  
  [RESPONSE_CODES.STATIONS_FOUND]: 200,
  [RESPONSE_CODES.STATION_NOT_FOUND]: 404,
  
  [RESPONSE_CODES.PAYMENT_SUCCESS]: 200,
  [RESPONSE_CODES.PAYMENT_FAILED]: 400,
  
  [RESPONSE_CODES.REVIEW_CREATED]: 201,
  [RESPONSE_CODES.REVIEWS_FOUND]: 200,
  [RESPONSE_CODES.REVIEW_NOT_FOUND]: 404,
  
  [RESPONSE_CODES.NOTIFICATIONS_FOUND]: 200,
  [RESPONSE_CODES.NOTIFICATION_MARKED_READ]: 200,
  [RESPONSE_CODES.NOTIFICATION_SENT]: 200,
  [RESPONSE_CODES.NOTIFICATION_NOT_FOUND]: 404,
  
  [RESPONSE_CODES.ACCOUNT_DELETED]: 200
};